Added preliminary MPR dep support

diff --git a/lolz b/lolz
--- a/lolz
+++ b/lolz
@@ -58,7 +58,33 @@ case "${1}" in
 			lolzy_message error "$INPUT does not exist"
 			exit 69
 		fi
-		lolzy_message info "installing $i..."
+		# it's about to get rough
+		# get list of deps
+		deps=( $("$MPR/rpc/?v=5&type=info&arg=$i" | jq '.results[].Depends' | sed 's/\,//g' | sed 's/\[//g' | sed 's/\]//g' | tr -d '"') )
+		# do a list of deps
+		for z in ${deps[@]}; do
+			# if the apt search fails, go to MPR search, but if apt search works, add to list of apt deps
+			if ! apt-cache search --names-only "$z"; then
+				# if the package exists in the MPR, add it to the mprdeps list
+				if curl --output /dev/null --silent --head --fail "$MPR/cgit/aur.git/plain/PKGBUILD?h=$z"
+					mprdeps+=("$z")
+				# else fail
+				else
+					lolzy_message error "$z is not a valid MPR or apt package"
+					exit 69
+				fi
+			# if apt works, add to the aptdeps list
+			else
+				aptdeps+="$z"
+			fi
+		done
+		if [[ ${#mprdeps[@]} -ne 0 ]]; then
+			lolzy_message info "Installing MPR dependencies first"
+			for i in ${mprdeps[@]}; do
+				lolz install "$i"
+			done
+		fi
+		lolzy_message info "Installing $i..."
 		mkdir -p $TMP
 		cd $TMP
 		git clone --depth=1 --single-branch --branch=master "$MPR/$i.git"
