Add unreachable MPR guard

diff --git a/stoke b/stoke
--- a/stoke
+++ b/stoke
@@ -46,6 +46,10 @@ fi
 
 case "${1}" in
   install)
+  	if ! curl --output /dev/null --silent --head --fail "$MPR"; then
+		stoke_message error "Cannot reach $MPR"
+		exit 1
+	fi
 	shift
 	if [[ $1 == "-y" ]]; then
 		export NOEDIT=1
