Replace some stuff

diff --git a/stoke b/stoke
--- a/stoke
+++ b/stoke
@@ -47,7 +47,7 @@ fi
 
 case "${1}" in
   install)
-  	if ! curl --output /dev/null --silent --head --fail "$MPR"; then
+	if ! curl --output /dev/null --silent --head --fail "$MPR"; then
 		stoke_message error "Cannot reach $MPR"
 		exit 1
 	fi
@@ -122,7 +122,7 @@ case "${1}" in
 		fi
 		if [[ ${#mprdeps[@]} -ne 0 ]]; then
 			stoke_message info "Installing MPR dependencies first"
-			for j in "${mprdeps[*]}"; do
+			for j in ${mprdeps[*]}; do
 				if ! stoke install "$j"; then
 					stoke_message error "$j failed to install"
 				fi
@@ -165,7 +165,7 @@ case "${1}" in
 		exit
 	else
 		echo "These packages can be upgraded:"
-		echo -e "\t${upgradable[@]}"
+		echo -e "\t${upgradable[*]}"
 		read -e -p "Do you want to continue? " choice
 		if [[ "$choice" == [Yy]* ]]; then
 			for i in ${upgradable[@]}; do
@@ -176,7 +176,7 @@ case "${1}" in
 				fi
 			done
 			if [[ "${#failed[@]}" -ne 0 ]]; then
-				stoke_message error "These packages failed to upgrade: ${failed[@]}"
+				stoke_message error "These packages failed to upgrade: ${failed[*]}"
 				exit 1
 			fi
 		else
@@ -199,7 +199,7 @@ case "${1}" in
 	exit
 	;;
   update)
-  	if ! sudo curl -L https://github.com/Henryws/stoke/raw/master/stoke -o /usr/local/bin/stoke; then
+	if ! sudo curl -L https://github.com/Henryws/stoke/raw/master/stoke -o /usr/local/bin/stoke; then
 		stoke_message error "Could not download stoke"
 		exit 1
 	fi
@@ -208,7 +208,7 @@ case "${1}" in
 		exit 1
 	fi
 	exit
-  	;;
+	;;
   help)
 	help_function
 	exit
