ITS FUCKING WORKING!!

diff --git a/stoke b/stoke
--- a/stoke
+++ b/stoke
@@ -60,35 +60,56 @@ case "${1}" in
 		URL="$MPR/cgit/aur.git/plain/PKGBUILD?h=$i"
 		VERSION=$(curl -s "$MPR/rpc/?v=5&type=info&arg=$i" | jq -C '.results[0].Version' | tr -d '"') &
 		if ! curl --output /dev/null --silent --head --fail "$URL"; then
-			stoke_message error "$INPUT does not exist"
+			stoke_message error "$i does not exist"
 			exit 1
 		fi
 		# it's about to get rough
 		# get list of deps
 		deps=( $(curl -s "$MPR/rpc/?v=5&type=info&arg=$i" | jq '.results[].Depends' | sed 's/\,//g' | sed 's/\[//g' | sed 's/\]//g' | tr -d '"' | tr -s ' ' | tr "\n" " " | tr -s ' ' | cut -d "%" -f 2) )
-		# do a list of deps
-		for z in "${deps[@]}"; do
-			# if the apt search fails, go to MPR search, but if apt search works, add to list of apt deps
-			if ! apt-cache show "$z" 2>/dev/null; then
-				# if the package exists in the MPR, add it to the mprdeps list
-				if curl --output /dev/null --silent --head --fail "$MPR/cgit/aur.git/plain/PKGBUILD?h=$z"; then
-					mprdeps+=("$z")
-				# else fail
+		if [[ $deps != "null" ]] && [[ $deps != "" ]]; then
+			# do a list of deps
+			for z in "${deps[@]}"; do
+				# if the apt search fails, go to MPR search, but if apt search works, add to list of apt deps
+				if ! apt-cache show "$z" >/dev/null; then
+					# if the package exists in the MPR, add it to the mprdeps list
+					if curl --output /dev/null --silent --head --fail "$MPR/cgit/aur.git/plain/PKGBUILD?h=$z"; then
+						mprdeps+=("$z")
+					# else fail
+					else
+						stoke_message error "$z is not a valid MPR or apt package"
+						exit 1
+					fi
 				else
-					stoke_message error "$z is not a valid MPR or apt package"
-					exit 1
+					aptdeps+=("$z")
 				fi
-			else
-				aptdeps+=("$z")
-			fi
-		done
-		if [[ ${#mprdeps[@]} -ne 0 ]]; then
-			stoke_message info "Installing MPR dependencies first"
-			for i in ${mprdeps[@]}; do
-				stoke install "$i"
 			done
 		fi
-		if [[ -z $aptdeps ]]; then
+		makedeps=( $(curl -s "$MPR/rpc/?v=5&type=info&arg=$i" | jq '.results[].MakeDepends' | sed 's/\,//g' | sed 's/\[//g' | sed 's/\]//g' | tr -d '"' | tr -s ' ' | tr "\n" " " | tr -s ' ' | cut -d "%" -f 2) )
+		if [[ $makedeps != "null" ]] && [[ $makedeps != "" ]]; then
+			# do a list of deps
+			for z in "${makedeps[@]}"; do
+				# if the apt search fails, go to MPR search, but if apt search works, add to list of apt deps
+				if ! apt-cache show "$z" >/dev/null; then
+					# if the package exists in the MPR, add it to the mprdeps list
+					if curl --output /dev/null --silent --head --fail "$MPR/cgit/aur.git/plain/PKGBUILD?h=$z"; then
+						mprdeps+=("$z")
+					# else fail
+					else
+						stoke_message error "$z is not a valid MPR or apt package"
+						exit 1
+					fi
+				else
+					aptdeps+=("$z")
+				fi
+			done
+		fi
+		if [[ ${#mprdeps[@]} -ne 0 ]]; then
+			stoke_message info "Installing MPR dependencies first"
+			for j in "${mprdeps[*]}"; do
+				stoke install "$j"
+			done
+		fi
+		if [[ -z ${aptdeps[*]} ]]; then
 			sudo apt-get install "${aptdeps[@]}"
 		fi
 		stoke_message info "Installing $i..."
